import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";
import { AppShell } from "@/components/sentinel/AppShell";
import { PageHeader, Panel } from "@/components/sentinel/states";
import { AlertCard } from "@/components/sentinel/panels";
import { useSentinel } from "@/store/sentinel";
import { Activity, Network, CheckCircle2, XCircle, AlertTriangle, Link as LinkIcon } from "lucide-react";

export const Route = createFileRoute("/investigations")({
  validateSearch: z.object({ case: z.string().optional() }),
  head: () => ({
    meta: [
      { title: "Investigations — SentinelAI" },
      { name: "description", content: "Review ongoing and resolved fraud cases generated by the SentinelAI detection engine." },
    ],
  }),
  component: Page,
});

function Page() {
  const { case: caseId } = Route.useSearch();
  const { cases, updateCaseStatus, anchorCaseToBlockchain } = useSentinel();
  
  const activeCases = cases
    .filter((a) => !["Confirmed Fraud", "False Positive", "Closed"].includes(a.status))
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    
  const resolvedCases = cases
    .filter((a) => ["Confirmed Fraud", "False Positive", "Closed"].includes(a.status))
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

  const selectedCase = cases.find((c) => c.case_id === caseId);

  return (
    <AppShell>
      <PageHeader 
        title="Investigations" 
        description="Review ongoing and resolved fraud cases generated by the SentinelAI detection engine." 
      />
      
      {selectedCase ? (
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="space-y-4 lg:col-span-2">
            <Panel title={`Evidence Panel: ${selectedCase.case_id}`} bodyClassName="p-4 space-y-6">
              <div className="flex items-start justify-between">
                <div>
                  <h3 className="text-lg font-medium text-foreground">{selectedCase.fraud_type}</h3>
                  <p className="text-sm text-muted-foreground">Trader: <span className="font-mono text-primary">{selectedCase.trader_id}</span> • Symbol: <span className="font-mono">{selectedCase.stock}</span></p>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-mono text-cyan">{(selectedCase.fraud_probability * 100).toFixed(1)}%</div>
                  <div className="text-xs text-muted-foreground uppercase tracking-widest">Fraud Prob</div>
                </div>
              </div>
              
              <div className="grid gap-4 md:grid-cols-3">
                <div className="rounded border border-border bg-elevated/50 p-3">
                  <div className="flex items-center gap-2 mb-2 text-sm text-muted-foreground"><Activity className="w-4 h-4 text-cyan" /> Anomaly Score</div>
                  <div className="text-xl font-mono text-foreground">{selectedCase.anomaly_score.toFixed(2)}</div>
                </div>
                <div className="rounded border border-border bg-elevated/50 p-3">
                  <div className="flex items-center gap-2 mb-2 text-sm text-muted-foreground"><Network className="w-4 h-4 text-primary" /> Network Risk</div>
                  <div className="text-xl font-mono text-foreground">{((selectedCase as any).network_risk || 0).toFixed(2)}</div>
                </div>
                <div className="rounded border border-border bg-elevated/50 p-3">
                  <div className="flex items-center gap-2 mb-2 text-sm text-muted-foreground"><AlertTriangle className="w-4 h-4 text-yellow-500" /> Comm Spike</div>
                  <div className="text-xl font-mono text-foreground">{selectedCase.risk_score > 85 ? "Detected" : "Normal"}</div>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-medium text-foreground mb-3 uppercase tracking-widest text-muted-foreground">Top Feature Impacts (SHAP)</h4>
                <div className="space-y-2">
                  {selectedCase.top_reasons && selectedCase.top_reasons.length > 0 ? (
                    selectedCase.top_reasons.map((reason, idx) => (
                      <div key={idx} className="flex items-center justify-between text-sm">
                        <span className="font-mono text-muted-foreground">{reason.feature}</span>
                        <div className="flex items-center gap-2">
                          <div className="h-1.5 w-24 bg-elevated rounded overflow-hidden">
                            <div className="h-full bg-cyan" style={{ width: `${Math.min(100, Math.abs(reason.impact) * 100)}%` }} />
                          </div>
                          <span className="font-mono w-12 text-right text-cyan">{(reason.impact).toFixed(2)}</span>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="text-sm text-muted-foreground italic">No SHAP explanations available for this case.</div>
                  )}
                </div>
              </div>
            </Panel>
            
            <Panel title="AI Recommendation" bodyClassName="p-4 bg-primary/5 border-primary/20">
              <p className="text-sm text-foreground">
                {selectedCase.severity === "Critical" 
                  ? "Escalate for insider-trading review immediately. Trigger blockchain anchoring to preserve evidence state." 
                  : selectedCase.severity === "High"
                  ? "Request additional communications metadata. Monitor further activity closely."
                  : "Close as low-risk anomaly."}
              </p>
            </Panel>
          </div>
          
          <div className="space-y-4">
            <Panel title="Actions" bodyClassName="p-4 space-y-3">
              {selectedCase.status !== "Confirmed Fraud" && selectedCase.status !== "False Positive" ? (
                <>
                  <button 
                    onClick={() => anchorCaseToBlockchain(selectedCase.case_id)}
                    className="w-full flex items-center justify-center gap-2 rounded bg-primary/20 border border-primary/50 p-2 text-sm font-medium text-primary hover:bg-primary/30 transition-colors"
                  >
                    <CheckCircle2 className="w-4 h-4" /> Approve Fraud & Anchor
                  </button>
                  <button 
                    onClick={() => updateCaseStatus(selectedCase.case_id, "False Positive", "Rejected by investigator")}
                    className="w-full flex items-center justify-center gap-2 rounded bg-elevated border border-border p-2 text-sm font-medium text-muted-foreground hover:bg-border transition-colors"
                  >
                    <XCircle className="w-4 h-4" /> Reject Alert
                  </button>
                  <button 
                    onClick={() => updateCaseStatus(selectedCase.case_id, "Under Investigation", "Requested more data")}
                    className="w-full flex items-center justify-center gap-2 rounded bg-elevated border border-border p-2 text-sm font-medium text-foreground hover:bg-border transition-colors"
                  >
                    Request More Data
                  </button>
                </>
              ) : (
                <div className="text-center p-4 border border-dashed border-border rounded">
                  <div className="text-sm font-medium text-muted-foreground mb-1">Case Resolved</div>
                  <div className="text-lg font-mono text-foreground">{selectedCase.status}</div>
                  {selectedCase.anchored && (
                    <div className="mt-3 flex items-center justify-center gap-1.5 text-xs text-primary bg-primary/10 py-1 px-2 rounded-full border border-primary/30">
                      <LinkIcon className="w-3 h-3" /> Blockchain Anchored
                    </div>
                  )}
                </div>
              )}
            </Panel>
            
            <Panel title="Case Information" bodyClassName="p-4 space-y-3 text-sm">
              <div className="flex justify-between"><span className="text-muted-foreground">Status</span><span className="font-medium text-foreground">{selectedCase.status}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Assigned</span><span className="font-mono">{selectedCase.assigned_to}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Created</span><span className="font-mono text-muted-foreground">{new Date(selectedCase.created_at).toLocaleString()}</span></div>
              {selectedCase.tx_hash && (
                <div className="pt-2 border-t border-border mt-2">
                  <div className="text-muted-foreground mb-1">Transaction Hash</div>
                  <div className="font-mono text-xs text-primary break-all">{selectedCase.tx_hash}</div>
                </div>
              )}
            </Panel>
          </div>
        </div>
      ) : (
        <div className="space-y-6">
          <Panel title="Active Cases" bodyClassName="p-3">
            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
              {activeCases.length === 0 ? (
                <div className="col-span-full p-8 text-center text-muted-foreground text-sm">
                  No active investigations.
                </div>
              ) : (
                activeCases.map((a) => <AlertCard key={a.case_id} alert={a} />)
              )}
            </div>
          </Panel>
          
          {resolvedCases.length > 0 && (
            <Panel title="Resolved Cases" bodyClassName="p-3 opacity-80">
              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                {resolvedCases.map((a) => <AlertCard key={a.case_id} alert={a} />)}
              </div>
            </Panel>
          )}
        </div>
      )}
    </AppShell>
  );
}

