/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BlockchainRouteImport } from './routes/blockchain'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TradersRouteImport } from './routes/traders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockchainRoute = BlockchainRouteImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersRoute = TradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/blockchain': typeof BlockchainRoute
  '/dashboard': typeof DashboardRoute
  '/engine': typeof EngineRoute
  '/explainability': typeof ExplainabilityRoute
  '/investigations': typeof InvestigationsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/traders': typeof TradersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/blockchain': typeof BlockchainRoute
  '/dashboard': typeof DashboardRoute
  '/engine': typeof EngineRoute
  '/explainability': typeof ExplainabilityRoute
  '/investigations': typeof InvestigationsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/traders': typeof TradersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/blockchain': typeof BlockchainRoute
  '/dashboard': typeof DashboardRoute
  '/engine': typeof EngineRoute
  '/explainability': typeof ExplainabilityRoute
  '/investigations': typeof InvestigationsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/traders': typeof TradersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/blockchain'
    | '/dashboard'
    | '/engine'
    | '/explainability'
    | '/investigations'
    | '/monitoring'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/traders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/blockchain'
    | '/dashboard'
    | '/engine'
    | '/explainability'
    | '/investigations'
    | '/monitoring'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/traders'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/blockchain'
    | '/dashboard'
    | '/engine'
    | '/explainability'
    | '/investigations'
    | '/monitoring'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/traders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BlockchainRoute: typeof BlockchainRoute
  DashboardRoute: typeof DashboardRoute
  EngineRoute: typeof EngineRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  InvestigationsRoute: typeof InvestigationsRoute
  MonitoringRoute: typeof MonitoringRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  TradersRoute: typeof TradersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blockchain': {
      id: '/blockchain'
      path: '/blockchain'
      fullPath: '/blockchain'
      preLoaderRoute: typeof BlockchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders': {
      id: '/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof TradersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BlockchainRoute: BlockchainRoute,
  DashboardRoute: DashboardRoute,
  EngineRoute: EngineRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  InvestigationsRoute: InvestigationsRoute,
  MonitoringRoute: MonitoringRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  TradersRoute: TradersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
